apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: warehouse-grafana
  namespace: warehouse-monitoring
  labels:
    app: warehouse-monitoring
    system: warehouse
spec:
  config:
    auth:
      disable_signout_menu: true
    auth.anonymous:
      enabled: true
    log:
      level: warn
      mode: console
    security:
      admin_password: admin
      admin_user: admin
  ingress:
    enabled: true