apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-service-monitor
  namespace: warehouse-monitoring
  labels:
    app: warehouse-monitoring
    system: warehouse
spec:
  namespaceSelector:
    matchNames:
      - warehouse
  selector:
    matchLabels:
      system: warehouse
  endpoints:
    - path: /metrics
      interval: 30s