apiVersion: v1
kind: Namespace
metadata:
  name:  argocd
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: argocd
  namespace: argocd
spec:
  targetNamespaces:
  - argocd
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: argocd-operator
  namespace: argocd
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: argocd-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: argocd-operator.v0.0.14
