apiVersion: v1
kind: Namespace
metadata:
  name:  warehouse-monitoring
  labels:
    system: warehouse
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: warehouse-monitoring
  namespace: warehouse-monitoring
spec:
  targetNamespaces:
  - warehouse-monitoring
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: prometheus
  namespace: warehouse-monitoring
spec:
  channel: beta
  installPlanApproval: Automatic
  name: prometheus
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: prometheusoperator.0.37.0
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: grafana-operator
  namespace: warehouse-monitoring
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: grafana-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: grafana-operator.v3.9.0